simple_slam_node:
  ros__parameters:
    simple_slam:
      tf_frame:
        map_frame: "map"
        robot_frame: "base_link"
      add_cell: false
      storage_map:
        publish_rate: 1.0 #[s]
        que_size: 5
      filter:
        voxelgrid_size: 0.2
        height_axis: "z"
        h_max: 1.5
        h_min: 0.1
      grid_map_info:
        resolution: 0.25 #[m] def 0.05
        # origin: [-5.0,-5.0,0.0]
        width: 25.0 #[m]
        height: 25.0 #[m]
