/**:
  ros__parameters:
    scan_matcher:
      type: 2 # [int] 0: ICP, 1: NDT, 2: GICP
      storage_map:
        publish_rate: 10.0 # [double] マップのPublishレート [Hz]

      voxel_grid:
        size: 0.1 # [double] ボクセルグリッドフィルタのサイズ [m]

      radius_outlier_removal:
        radius: 0.5 # [double] 外れ値除去の半径 [m]
        min_neighbors: 2 # [int] 外れ値とみなす最小近傍数

      keyframe:
        min_trans: 0.5 # [double] キーフレームを更新する最小並進移動量 [m]
        min_rot: 0.3 # [double] キーフレームを更新する最小回転移動量 [rad]

      local_map:
        window_size: 10 # [int] ローカルマップを構築するためのウィンドウサイズ（フレーム数）

      stop_velocity:
        trans: 0.01 # [double] 停止状態とみなす並進速度の閾値 [m/s]
        rot: 0.008 # [double] 停止状態とみなす回転速度の閾値 [rad/s]
